name: Update Total Commit Count

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Atualizado para v4

      - name: Get total commit contributions
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          username="${{ github.repository_owner }}"
          
          query="query { user(login: \"$username\") { contributionsCollection { totalCommitContributions } repositoriesContributedTo(contributionTypes: [COMMIT]) { totalCount } } }"
          
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -X POST -d "{\"query\": \"$query\"}" \
            https://api.github.com/graphql)
          
          total=$(echo "$response" | jq '.data.user.contributionsCollection.totalCommitContributions')
          
          echo "TOTAL_COMMITS=$total" >> $GITHUB_ENV

      - name: Update README badge
        run: |
          
          if [ "${{ env.TOTAL_COMMITS }}" != "null" ] && [ ! -z "${{ env.TOTAL_COMMITS }}" ]; then
              echo "Atualizando para ${{ env.TOTAL_COMMITS }}"
              
              sed -i "s/Commits%20Totais-[^)]*-blue/Commits%20Totais-${{ env.TOTAL_COMMITS }}-blue/g" README.md
          else
              echo "Erro: O valor de TOTAL_COMMITS veio nulo ou vazio."
              exit 1
          fi

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update total commit badge: ${{ env.TOTAL_COMMITS }}" || exit 0
          git push
